name: msmc2-snakemake
channels:
  - bioconda
  - conda-forge
  - genomedk
  - nodefaults
dependencies:
  - python
  - bioconda::snakemake
  - bioconda::samtools
  - bioconda::bcftools
  - genomedk::msmc2
  - bioconda::snakemake-executor-plugin-slurm
  - conda-forge::ldc=1.28
